import{a as d,S as p,i as a}from"./assets/vendor-GgwdjDaY.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const f="/.netlify/functions/pixabay";function g(r){return d.get(f,{params:{q:r}}).then(o=>o.data)}const l=document.querySelector(".gallery"),m=new p(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const o=r.map(({webformatURL:n,largeImageURL:i,tags:e,likes:t,views:s,comments:c,downloads:u})=>`<li class="gallery-item">
          <a class="gallery-link" href="${i}">
            <img class="gallery-image" src="${n}" alt="${e}" loading="lazy" />
          </a>
          <div class="card-meta">
            <p><span>Likes</span><strong>${t}</strong></p>
            <p><span>Views</span><strong>${s}</strong></p>
            <p><span>Comments</span><strong>${c}</strong></p>
            <p><span>Downloads</span><strong>${u}</strong></p>
          </div>
        </li>`).join("");l.innerHTML=o,m.refresh()}function h(){l.innerHTML=""}function L(){const r=document.querySelector(".loader");r&&r.classList.remove("loader-hidden")}function S(){const r=document.querySelector(".loader");r&&r.classList.add("loader-hidden")}const q=document.querySelector(".form"),b=document.querySelector('input[name="search-text"]');q.addEventListener("submit",v);function v(r){r.preventDefault();const o=b.value.trim();if(!o){a.warning({title:"Warning",message:"Please enter a search term.",position:"topRight"});return}h(),L(),g(o).then(n=>{if(!n.hits||n.hits.length===0){a.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(n.hits)}).catch(n=>{a.error({title:"Error",message:`Unable to load images. ${n.message}`,position:"topRight"})}).finally(()=>{S()})}
//# sourceMappingURL=index.js.map
